### PR TITLE
DTSSTCI-731

### PR DESCRIPTION
**Pull request by pr00279**
### Change description

Added some indentation and enabled the display of inline error messages on file upload pages.

### JIRA link

https://tools.hmcts.net/jira/browse/DTSSTCI-731

### CODE REVIEW

**Comment by pr00279** [comment]
image
Just an example of one of the errors; the other errors will show in the same place

**Comment by pr00279** [comment]
image

Just an example of one of the errors on the upload appeal form page; the other errors will show in the same place

**Comment by pr00279** [comment]
image

Just an example of one of the errors on the upload supporting documents page; the other errors will show in the same place

**Comment by pr00279** [comment]
image

Just an example of one of the errors on the upload additional documents page; the other errors will show in the same place

**Review by gmmagruder — APPROVED** [review]

**Review by tomxelliott — APPROVED** [review]

**Pull request merged**
